### ISSUE TITLE
how do I get the text out?

### ISSUE THREAD

**Issue by sjoyce1** [Mekire/pygame-textbox#1]
Hi there.
Being able to change the color of the screen and text is sweet, but what if I wanted to do something with the input that was actually useful?  You know, like return a string or something?

**Comment by Mekire** [comment]
You interact with the textbox via a callback function.  In the example this was the `change_color` function passed with the `command` keyword argument.  

```python
self.input = TextBox((100,100,150,30),command=self.change_color,
                      clear_on_enter=True,inactive_on_enter=False)
```

Using callback functions is a pretty common technique in GUI programming.
If you have a specific use case that you can't figure out I can try and write you up an example that demonstrates usage.  You could technically check the value of the box's `final` attribute instead of the callback but this is not the intended usage.

**Comment by sjoyce1** [comment]
I did one of these:
```
def getText(self,id,text):
    self.gotText_flag = True
    self.gotText = text
```
and called it with
```
self.input = TextBox((100,100,150,30),
    command=self.getText,
    clear_on_enter=True,
    inactive_on_enter=False)
```
although I gotta work on the flag bits still.

**Comment by Mekire** [comment]
Looks like it should work fine.  Let me know if you have any issues.
